### ISSUE TITLE
Will this be updated?

### ISSUE THREAD

**Issue by sido378** [bluehexagons/foodguide#1]
Hi, 
Sorry, couldn't find another way to contact you.
Will you update this to the Shipwrecked DLC?
Otherwise, i might do it, if you are okay with it.

**Comment by bluehexagons** [comment]
Hey; I'll go through any pull requests that get opened, or if specific issues get added I'll try to find the time to make the changes myself. Several issues were accidentally lost when I moved this from Google Code to GitHub, and since none of those have been re-opened there are probably a few things that are incorrect in the current version too. I should probably take the time to add a contributing file to the repository at some point so people are aware.
