### ISSUE TITLE
Transition to TypeScript

### ISSUE THREAD

**Issue by levy9527** [bluehexagons/foodguide#14]
Now all javascript is in one large file, which is more than 4000 lines. I think it's hard to maintain or fix bugs. Shall we use gulp or webpack to split the source code into serveral small files

**Comment by bluehexagons** [comment]
I hadn't anticipated the guide becoming as large as it did when I started, and at this point it seems like it'd be more trouble than it's worth to split it into separate files. It would also add an extra step for someone wanting to contribute if they didn't have the build tools or didn't feel like installing them. I don't personally have experience using gulp or webpack, so that'd be another barrier.

**Comment by levy9527** [comment]
That's alright, I can help. These tools depend on node.js, which is easy to install and run. 
I have the experience using these tools, but I am not familiar with the source code now. I will try to split them.  It may need your help. 
By the way, using what tools is not very important. The goal is to split source code into several files, such as foodList.js, recipeList.js and so on. I believe in this way everyone can easy to find the code. 
If you like, not using tools, just using pure javascript is also OK😀

**Comment by bluehexagons** [comment]
I appreciate the effort, and I can give you help if you end up needing it. The most important pieces to separate are definitely the food and recipe list like you mentioned, so that'd be the easy place to start. I considered moving the code to TypeScript a while back since that's what I'm using more of lately for work, but decided it'd probably alienate some potential contributors and opted against it.

**Comment by levy9527** [comment]
Using TypeScript is OK. Just code in your style. Cause you're the owner😬

**Comment by bluehexagons** [comment]
The original request, splitting code, is now done using modules, and at this point I prefer the simplicity of not requiring any tooling for Node or TypeScript compilation.
