### ISSUE TITLE
Unclear ingredient summary in Simulator tab

### ISSUE THREAD

**Issue by bluehexagons** [bluehexagons/foodguide#16]
The Simulator tab always reflects an ingredient's best values (if its cooked form has better stats), but lacks an indicator when it has done so. May consider making this an option in a later settings tab.

**Comment by levy9527** [comment]
Since in the simulator tab, food has cooked and uncooked form, I still think best value is not necessary. 

Just take Red Cap for example:
If use best value, we get 1 Health and 12.5 Hunger. It seems the Red Cap is not a bad thing.
However, When uncooked Red Cap eaten, we will actually get 12.5 Hunger and -20 Health, that's  not so good. And, If we eat cooked Red Cap, we can get just 1 Health and no Hunger. That is to say, the Red Cap is something useless.  

Generally speaking, the only reason for me the collect the Red Cap is to cook Meatballs ------  1 monster meat and 3 Red Caps. 
In this situation: 
with best value, we  may think that Meatballs is just so so.
without best value, we can see that Meatballs is a pretty nice choice.

**Comment by bluehexagons** [comment]
While that's true, I still think it's fair to compare the best case scenario of eating food compared to adding it to the crock pot. There are some exceptions to that (like mushrooms, which you've pointed out) which could be worked in.

If something can be cooked and give more food/hunger, but the cooked form can't be used to make the desired recipe, then it's useful to easily compare the optimal use of the food to what the recipe produces. And since a lot of foods spoil more slowly when they're raw, it's more likely to cook them raw, in which case it's still useful to compare the cooked stats since if they were eaten instead of used in the crock pot then they'd likely be cooked first.

To me, the problem here is mostly with how the guide communicates this, rather than that it's doing the math by itself. Perhaps the best solution would be to have two rows, one that shows the exact stats of the ingredients used, and another that shows them with optimal stats (if cooked is better).

**Comment by levy9527** [comment]
Alright, I didn't realize that there're some recipes that need uniq form: cooked or uncooked. 
Now I understand what you mean.

**Comment by 6lancmange** [comment]
I wanted to add a new issue about the Combined row giving wrong information, but it appears you know about it and it's intended (although calling it "combined" is definitely not accurate). I guess I understand using the better stats option – although it's not preferable when you're trying to figure out whether it's better to add ingredients into the crock pot or just eat them separately – but it would only make sense if the values all belong to one variation of an item, such as raw or cooked mushroom. But I noticed that they are actually mixed, which makes it useless even if you assume that you're not adding actual values of the exact ingredients put into the simulator.

For example:
![image](https://user-images.githubusercontent.com/26997029/68093263-02606f00-fe94-11e9-8ad3-3c2ac820dc40.png)
![image](https://user-images.githubusercontent.com/26997029/68093274-2459f180-fe94-11e9-99ae-43e743e38913.png)
The combined values are impossible to get, because the health and hunger are the values of the raw Green Cap, while sanity comes from the Cooked Green Cap. As a side note, including perish time would be cool.

**Comment by bluehexagons** [comment]
I switched from tracking "best" to "potential", so cooked foods won't consider their raw versions. I also added a second total row that only uses the ingredients selected. Comparisons are now made to the base total, instead of best/potential.
