### ISSUE TITLE
wobster in statistics analyzer

### ISSUE THREAD

**Issue by ungoliant** [bluehexagons/foodguide#2]
although dead wobsters cannot be used in crockpot, counting live wobsters in the statistics analyzer as 0 hunger and health is somewhat misleading, and results in all kinds of recommendations in the statistics analyzer that just don't make sense.  

wobsters should show up in bonus health/hunger calculations as 12.5 hunger, 1 health, not 0 heatlth, 0 hunger.

**Comment by bluehexagons** [comment]
That's a fair point. I haven't played enough Don't Starve lately to have been able to catch this myself. It's kind of in the same category of the statistics analyzer using raw + cooked versions of a few things for recipe reasons, and it isn't always fair to use the lower raw values. Mushrooms and similar ingredients can be a bit annoying, too.

**Comment by bluehexagons** [comment]
I just pushed code that improves this situation quite a bit. It calculates idealized stats for each food; so, if it can be dried or cooked (or has a raw/wet version), it uses the best stat out of all of those. I also have it displaying this value on food tables now for raw food, since it's convenient to know.
