### ISSUE TITLE
New recipes added for DST Warly

### ISSUE THREAD

**Issue by hyiltiz** [bluehexagons/foodguide#26]
Some recipes are from Hamlet/SW, and some are completely new. Here is the new additions [1]:

```
 Creamy Potato Purée
- 2 Potato, 1 Garlic, 1 Filler
- 37,5 Hunger, 20 Health, 33 Sanity
-Filler can't be Meat or Twigs

Asparagus Soup
- 1 Asparagus, 2 Veggies, 1 Filler
- 18,8 Hunger, 20 Health, 5 Sanity
-Filler can't be Meat, Ice or Twigs

Vegetable Stinger
- 1 Asparagus, 2 Veggie, 1 Ice
- 25 Hunger, 3 Health, 33 Sanity

Banana Pop 
- 1 Cave Banana, 1 Ice, 1 Twig, 1 Filler
- 12,5 Hunger, 20 Health, 33 Sanity
-Lowers Temperature
-Filler can't be Meat

Ceviche
- 2 Fish, 1 Ice, 1 Filler
- 25 Hunger, 20 Health, 5 Sanity
- Lowers Temperature
-Filler can't be Meat or Twigs

Salsa Fresca
- 1 Tomato, 1 Onion, 2 Fillers
- 25 Hunger, 3 Health, 33 Sanity
-Fillers can't be Meat or Twigs

Stuffed Pepper Poppers
- 1 Pepper, 1 Meat, 2 Fillers
- 25 Hunger, 30 Health, -5 Sanity
-Fillers can't be another Meat, 2 Morsels or Twigs

Portable Crock Pot Exclusive Recipes:

Grim Galette
- 2 Nightmare Fuel, 1 Onion, 1 Potato
- 25 Hunger
-Current Health and Sanity values are swapped.
-Works on Wormwood

Volt Goat Chaud-Froid
- 1 Volt Goat Horn, 2 Honey, 1 Filler
- 37,5 Hunger, 3 Health, 10 Sanity
-Electrical DMG is added.
-Filler can't be Meat

Glow Berry Mousse
- 1 Glowberry, 1 Fruit, 2 Fillers
- 37,5 Hunger, 3 Health, 10 Sanity
-Emits light around the player.
-Fillers can't be Meat or Twigs
-Berries count as 0,5 Fruit

Fish Cordon Bleu
- 2 Frog Legs, 2 Fish
- 37,5 Hunger, 20 Health, -10 Sanity
- Immediately sets Wetness to 0
- Become Waterproof

Hot Dragon Chili Salad
- 1 Dragonfruit, 1 Pepper, 2 Fillers
- 25 Hunger, -3 Health, 10 Sanity
- Provides warmth for 1 day
-Will Overheat outside of Winter.
-Fillers can't be Meat or Twigs

Asparagazpacho
- 2 Asparagus, 2 Ice
- 25 Hunger, 3 Health, 10 Sanity
- Lowers temperature for 1 day
- Will Freeze outside of Summer

Puffed Potato Souffle
- 2 Potato, 1 Egg, 1 Filler
- 37,5 Hunger, 20 Health, 15 Sanity
Filler can't be Meat or Twigs

Monster Tartare
- 2 Monster Meat, 2 Fillers
- 62,5 Hunger, -20 Health, -20 Sanity
-Fillers can't be Twigs

Fresh Fruit Crepes
- 2 Fruit, 1 Butter, 1 Honey
- 150 Hunger, 60 Health, 15 Sanity

Bone Bouillon
- 2 Bone Shards, 1 Onion, 1Filler
- 150 Hunger, 32 Health, 5 Sanity
-Filler can't be Twigs

Moqueca
- 2 Fish, 1 Onion, 1 Tomato
- 112,5 Hunger, 60 Health, 33 Sanity
```

[1] https://forums.kleientertainment.com/forums/topic/109451-fixed-warlys-recipes/

Additionally, if you could write a parser for the `recipes.lua` that creates JSON needed for your site and extract the textures automatically, it would be future-proof; new recipe additions only means running the parser once more.

**Comment by bluehexagons** [comment]
I'll add the new content when I'm able to if no one has submitted a pull request by then. I just moved across the country, so I'm a bit short on spare time.

As for the parser suggestion, it's so easy to copy the data in manually that I don't imagine it would save time in the long run. That'd be more of a project for if I, or someone else, just felt like doing it for fun. I do have a few ideas for this project if I ever get around to it, so I might add that to my list.

**Comment by 6lancmange** [comment]
@bluehexagons I was trying to figure out a way to make some sort of list or tool for finding recipes and I found yours. Thank you so much! But when I noticed some ingredients and recipes were missing, I decided to try adding them, and I'm having trouble understanding some parts. What exactly is the difference between "isveggie" and "veggie", and what are they used for? I get that "veggie" is the value an ingredient has, but I can't figure out the "isveggie".

I'm comparing three items:
- Carrot – typical vegetable
  - listed on the wiki page for vegetables, usable in the crockpot, value of 1
  - isveggie: true, veggie: 1
  - all of the above is also the case for the cooked carrot
- Butterfly Wings – not a real vegetable, but used as such
  - not listed as a vegetable, usable in crockpot, even has a recipe that requires it, value – ???
  - can be used in recipes as filler, but does it also work as a vegetable? Stuffed Eggplant requires vegetables and accepts Butterfly Wings, while Ratatouille also requires vegetables, but specifically excludes Butterfly Wings (along with Mandrake, which I'll get to)
  - isveggie: true, "veggie" not used
  - can't be roasted
  - Wigfrid won't eat them
- Mandrake – not a typical vegetable, can be used as one, but sometimes restricted, just like Butterfly Wings
  - listed as vegetable, usable in crockpot (has specific recipe), vegetable value of 1
  - can be roasted and the above is true for both raw and cooked versions, however cannot be planted on a farm since it doesn't have seeds – I suspected this was relevant, but since Butterfly Wings also can't be farmed, I don't think that's the case
  - "isveggie" not used, veggie: 1
  - Wigfrid will also not eat it (according to a forum post I found)

So what is the "isveggie" for? I can't find a clear common feature that the ingredients with this set to true have (or the ones that don't have it listed).

**Comment by bluehexagons** [comment]
I don't remember for sure, but I think it has something to do with it checking the box on veggies being present but not counting as a numeric veggie value. I believe it was borrowed directly from Don't Starve's data files.

**Comment by 6lancmange** [comment]
I would like to add the recipes that are exclusive to DST, but can only be made in the Portable Crock Pot, so they require Warly. So here's the problem: is the mode 'warly' or 'together'?

Also, Monster Tartare can be made in DST as well as SW, but it has different requirements and cook time, and different results for Health, Hunger, and Sanity. How to reflect that?

**Comment by lakhnishMonster** [comment]
"Is it possible to make two versions within one entry, or simply add the same recipe, but with mode 'together' (this still doesn't solve the Portable Crock Pot ones)?"

If this were to be done, wouldn't this just lead to a double entry when selecting the DST mask? One entry with the single-player DS/RoG version & another for the DST version? 

This is mainly an issue for recipes that exist both in DS:RoG and DST, like Butter Muffin and Guacamole, since the DST masks also uses the DS Vanilla and RoG mask (I think its only these two recipes as well, need to double check).

For foods/recipes that do exist in DST but not in DS:RoG (such as the Vegetable Stinger or Asparagus Soup from Hamlet), you can most likely get away with a new entry just for DST since the Hamlet mask isn't chosen when you select DST. This would also apply to Monster Tartar & Banana Pops, which have a different recipe from the SW versions, but wouldn't matter for their DST versions for the same reason.

As for the Warly mask, he would probably need another mask for DST honestly, if only because Warly works differently in DST. 

He can only eat foods with the preparedfood tag (i.e. all crockpot foods) which needs to be worked out here on the simulator. Also, nothing should show up when the DST Warly mask choses the Food List Tab on the simulator since he can't eat them anyways.

He also doesn't get the same food penalties/bonus modifiers for eating foods like SP, which the SP Warly mask applies when you chose it.

**Comment by 6lancmange** [comment]
I'm not sure there's a problem with vanilla and RoG, it seemed like the only recipes that have differences in DST are those that were previously exclusive to SW or Hamlet, although I could be wrong. But, right, you can't choose both DST and SW/Hamlet, so I gueeess maybe adding two entries would be okay.

As for Warly, I'm not wondering about what he can eat, I don't think that's reflected anywhere. It looks like his mask is only for including the recipes that can only be made in the Portable Crock Pot. Is it possible for him to craft one and give it to another character, who can then cook in it? Can he give his exclusive meals to other characters? I assume both are possible.

My issue is that mode 'warly' is, what I assume, "recipes that require Portable Crock Pot", originally added in SW. The new recipes are only in DST, though (while still requiring the item). I think the modes might need another rework?

**Comment by lakhnishMonster** [comment]
I listed what he could eat for those that didn't know about it ( just in case for those that haven't been following the game anymore). While Warly is able to share his meals with other players, he's the only one that can make those meals in the Portable Crockpot. 

I was not clear on Warly's food restriction it seems. The issue/problem is that his ability to only eat crockpot foods is not reflected in the simulator currently. He also doesn't get the crockpot meal stat bonus like in singleplayer. This would be need to be addressed for a DST Warly mode, was what I was trying to get at. (A new mask for just DST Warly was just a suggestion as well since it was the simplest solution I could think of to reflect both changes to Warly & the DST foods that are exclusive to Warly's Portable Crockpot).

**Comment by bluehexagons** [comment]
It sounds like Warly may need to be a special case handled outside of the regular mode selection, and DST requires some extra logic too. Is DST the more popular way to play right now?

**Comment by lakhnishMonster** [comment]
As per Steam Stats, by a large amount (about 1-3k people avg for DS, about 7-9k people for DST). 

Also, for about the past year starting about Feb. 2019, DST has been receiving an update every month in the forms of either a character reworks or DLC characters for that month. This Thurdsay PST is the 3rd DLC character of the 4 planned DLC characters, and we've only got 4 character reworks so far (Winona, Willow, Woodie & a reworked Warly to DST).

They are also doing another major content update to DST like A New Reign, with this one being dubbed Return of Them. The third beta for RoT should be soon as well, with more to come about every 6 weeks (4 weeks of work, 2-ish weeks beta).

**Comment by bluehexagons** [comment]
So DST will continue to diverge from DS then. I'll think about how best to deal with individual recipes being different and try to set some time aside to work on it if no one else ends up taking on the task. I'll make an issue to track that.
