### ISSUE TITLE
Feijoada doesn't require clicking a meat item, but it should

### ISSUE THREAD

**Issue by 6lancmange** [bluehexagons/foodguide#28]
Feijoada shows up as doable as soon as you select three Bean Bugs, cooked or not. The recipe requires a meat ingredient, but you don't have to select one on the page.

The similar recipe of Caviar works as intended – apart from three of (Cooked) Roe you have to choose a veggie. I noticed these while trying to figure out how to require at least two potatoes raw or cooked, not necessarily two raw or two cooked, so it would be great to solve this as well.

**Comment by 6lancmange** [comment]
It seemed like it was fixed when I was checking how the raw/cooked adding worked, and it turns out that sometimes it requires meat and sometimes it doesn't.

Bean Bugs x 3 – not enough, needs meat
Cooked Bean Bugs x 3 – enough for the recipe to show up and nearly any filler will do
Bean Bugs x 1 and Cooked Bean Bugs x 2 – enough, same as above
Bean Bugs x 2 and Cooked Bean Bugs x 1 – enough, same as above

However, Cooked Bean Bugs x 4 is not accepted. Neither is Bean Bugs x 2 and Cooked Bean Bugs x2, or 3 raw + 1 cooked, BUT 3 cooked and 1 raw shows up valid.

**Comment by lakhnishMonster** [comment]
Funny enough, this report should be for Klei rather than the simulator xD.

If you do this what the bugged before was as above, it actually works in-game. 

This would be something that Klei would need to address first before the simulator, but good luck trying to get that fixed since they haven't touched DS at all since ~March 2019.

For now, a reversion was made to follow Klei's version, but a note was made so that people can see this in the simulator.

**Comment by 6lancmange** [comment]
Oh, I didn't know about that! Well, then the correction wasn't really necessary.
