### ISSUE TITLE
Some recipes differ between DST and single player

### ISSUE THREAD

**Issue by bluehexagons** [bluehexagons/foodguide#32]
Some ingredients, names, and possibly other values need to change when selecting Don't Starve Together vs single player.

**Comment by lakhnishMonster** [comment]
There are quite a few apparently, at least on the Crockpot level (and the fact that Asparagus exists both in DST and Hamlet). 

This just lists if there's a difference in crockpot recipes and/or names for foods that exist in the single-player and DST version, including the SW and Hamlet Masks, since some recipes from there made their way to DST. More so to give a brief overview than anything.

**DS vs. DST:**
-butterflymuffin: Different recipes. 
-taffy: It's a Goodie Foodtype in DST (is it an issue for this simulator though?)
-waffles: Different recipes (because of Juicy Berries). 

**RoG vs. DST:**
-trailmix: Different recipes (b/c Juicy Berries).
-guacamole: Different recipes. 

**SW vs. DST:**
-bananapops: Different recipes. 
-ceviche: Different recipes. 

**SW Warly vs. DST:** 
-sweetpotatosouffle: Different recipes and prefab names. DST renamed it to potatosouffle. 
-monstertartar: Different recipes. .

**Hamlet vs. DST:**
-asparugus: No differences in stats. Just exists in both now.
-asparagussoup: Different recipes.
-spicyvegstinger: Different recipes & prefab names. DST renamed it to vegstinger.

**Comment by lakhnishMonster** [comment]
@bluehexagons 

**Problem:**
My understanding of the masks is that its building off of previous versions/DLCs of the game.
So the RoG mask will be RoG + DS foods, SW will be SW + RoG + DS foods, Hamlet will be Ham + SW +RoG +DS foods.

The issue is with DST. It's a little bit of SW, little bit of Hamlet, some differences between DST's recipes and DS/RoG recipes.

**Suggestion:**
My suggestion is this: make it so that DST isn't built off from other masks. Instead, in the section we have for DST, we could just re-list all the recipes in the game and insert mode: 'together' in the recipe/food item. 

That would also address the issue for DST Warly, where it could just build off of this adjusted DST mask instead of trying to figure out which parts of SP DS is repeated/different in DST.

This shouldn't lead to double entries when choosing between the modes and wouldn't require something super fancy logic to figure out what recipes are repeated/different in DST; instead it just uses what we already have in place, with some (hopefully) slight adjustments to the masks.

**Potential issue with suggestion:**
The only issue that I would see with this solution is the image detection for recipes that exist in both games, have the same name, but different recipes (or food items that exists in Hamlet and DST, ie. Asparagus). 

For example, DS and DST both have trail mix, but have different recipes for both. Will the simulator use the same trail mix png for both, or will it cause issues?

DST just continues to differentiate from DS, especially since they added more SW foods to DST in the latest beta: Hook, Line, & Inker.
