### ISSUE TITLE
StatisticsAnalyzer default/bulk ingredient disable list

### ISSUE THREAD

**Issue by ElliotHolt** [bluehexagons/foodguide#9]
Honeycomb doesn't have any H/H/S stats associated with it, so it gets added as an optimal ingredient in every sweetener suggestion with most-optimal recipes including maximum allowable honeycombs. 

You can turn the ingredient off so the page is working as intended, but I think this represents unexpected behavior.

Somewhat unrelated (and probably more of a feature-request), but seeing sanity and sanity+ in the analyzer would be dope.

**Comment by bluehexagons** [comment]
I'd considered adding a way to bulk disable things that didn't really make sense to add to the crock pot under normal circumstances, but ended up scrapping the idea, partially because I haven't played much in a very long time so I don't really know what would fit. I probably won't work on this, but I'll leave the ticket open in case someone else has a good idea and wants to implement a fix.

As for adding sanity, that should be in another issue to track it independently. I don't plan on adding it since it's pretty rare to be a use case for the crock pot, or at least not to my knowledge; all of the main +sanity recipes would probably be made deliberately. It might add a bit to the computation time, too, which is already pretty long.

**Comment by ElliotHolt** [comment]
I updated the title and added a ticket for the other suggestion.

Maybe a simple quality of life change would be an initial-default disable list that contained just the honeycomb. 

This actually acted as a trigger to learn how to use the filter list, and on further thought, there's nothing really incorrect with the information displayed. The whole thing struck me as odd until I just realized the honeycomb is just a weird food item and I didn't realize it's interaction until I saw the results in the analyzer.

Thanks for the feedback.

**Comment by bluehexagons** [comment]
The filter experience needs more work to be enjoyable, but I added a default exclusion option for food (and recipes, but none are flagged) and pre-populated it with things that made sense to me as a temporary solution. I think it also helps make it more obvious that the filters exist, but instruction somewhere visible would be best for that purpose.
